### ISSUE TITLE
UX/UI: Display of Train "Route" is a little unintuitive

### ISSUE THREAD

**Issue by glbotu2** [ElementWeather/ProjectIceCloud#9]
Selecting a service and drilling down into a service - the "dot with circle inside" and "dot with filled in circle inside" look more like they're indicating the current location of the train, rather than the start and end of the service. I get that you've gone for "source" and "sink", which is a fairly traditional engineering view of what start and end look like, however Mr Harry Beck put paid to that as the common means of displaying this concept. 

Honestly, just not showing it, and let people assume that "top to bottom" means the route of the train is obvious enough.

**Comment by ElementWeather** [comment]
Implemented in next version for both UI simplicity and performance reasons.
